#! /usr/bin/env python3
#

import numpy as np
import matplotlib.pyplot as plt
import platform
import time
import sys
import os
import math
from mpl_toolkits.mplot3d import Axes3D
from sys import exit

sys.path.append(os.path.join("../"))
from base import plot2d, plotocc
from timestamp.timestamp import timestamp

from i4lib.i4vec_print import i4vec_print
from i4lib.i4mat_print import i4mat_print, i4mat_print_some
from r8lib.r8vec_print import r8vec_print
from r8lib.r8mat_print import r8mat_print, r8mat_print_some
from r8lib.r8mat_write import r8mat_write


def perrin(n):

    # *****************************************************************************80
    #
    # PERRIN returns the first N values of the Perrin sequence.
    #
    #  Discussion:
    #
    #    The Perrin sequence has the initial values:
    #
    #      P(0) = 3
    #      P(1) = 0
    #      P(2) = 2
    #
    #    and subsequent entries are generated by the recurrence
    #
    #      P(I+1) = P(I-1) + P(I-2)
    #
    #    Note that if N is a prime, then N must evenly divide P(N).
    #
    #  Example:
    #
    #    0   3
    #    1   0
    #    2   2
    #    3   3
    #    4   2
    #    5   5
    #    6   5
    #    7   7
    #    8  10
    #    9  12
    #   10  17
    #
    #  Licensing:
    #
    #    This code is distributed under the GNU LGPL license.
    #
    #  Modified:
    #
    #    07 May 2015
    #
    #  Author:
    #
    #    John Burkardt
    #
    #  Reference:
    #
    #    Ian Stewart,
    #    "A Neglected Number",
    #    Scientific American, Volume 274, pages 102-102, June 1996.
    #
    #    Ian Stewart,
    #    Math Hysteria,
    #    Oxford, 2004.
    #
    #    Eric Weisstein,
    #    CRC Concise Encyclopedia of Mathematics,
    #    CRC Press, 1999.
    #
    #  Parameters:
    #
    #    Input, integer N, the number of terms.
    #
    #    Output, integer P(N), the first N terms of the sequence.
    #

    p = np.zeros(n)

    if (0 < n):
        p[0] = 3

        if (1 < n):
            p[1] = 0

            if (2 < n):
                p[2] = 2

                for i in range(3, n):
                    p[i] = p[i - 2] + p[i - 3]

    return p


def perrin_test():

    # *****************************************************************************80
    #
    # PERRIN_TEST tests PERRIN.
    #
    #  Licensing:
    #
    #    This code is distributed under the GNU LGPL license.
    #
    #  Modified:
    #
    #    07 May 2015
    #
    #  Author:
    #
    #    John Burkardt
    #

    n = 20

    print('')
    print('PERRIN_TEST')
    print('  Python version: %s' % (platform.python_version()))
    print('  PERRIN computes the Perrin numbers.')

    p = perrin(n)

    i4vec_print(n, p, '  The Perrin sequence:')
#
#  Terminate.
#
    print('')
    print('PERRIN_TEST:')
    print('  Normal end of execution.')
    return


if (__name__ == '__main__'):
    from timestamp import timestamp
    timestamp()
    perrin_test()
    timestamp()
