curl.exe https://www.seizando.co.jp/wp-content/uploads/2018/09/SemiSubCircle_q-method.f.txt       -o SemiSubCircle_q-method.f        
curl.exe https://www.seizando.co.jp/wp-content/uploads/2018/09/SemiSubCircle_Phi-method.f.txt     -o SemiSubCircle_Phi-method.f      
curl.exe https://www.seizando.co.jp/wp-content/uploads/2018/09/HydroFoil_q-method.f.txt           -o HydroFoil_q-method.f            
curl.exe https://www.seizando.co.jp/wp-content/uploads/2018/09/WVSingulars.Subs.f.txt             -o WVSingulars.Subs.f              
curl.exe https://www.seizando.co.jp/wp-content/uploads/2018/09/SemiSub-LewisForm_Phi-method.f.txt -o SemiSub-LewisForm_Phi-method.f  
curl.exe https://www.seizando.co.jp/wp-content/uploads/2018/09/FullSub-LewisForm_Phi-method.f.txt -o FullSub-LewisForm_Phi-method.f  
curl.exe https://www.seizando.co.jp/wp-content/uploads/2018/09/WVSingulars.Subs.f.txt             -o WVSingulars.Subs.f              
curl.exe https://www.seizando.co.jp/wp-content/uploads/2018/09/WaveMakerBoard.f.txt               -o WaveMakerBoard.f                
curl.exe https://www.seizando.co.jp/wp-content/uploads/2018/09/WVSingulars.Subs.f.txt             -o WVSingulars.Subs.f              
