double *r8mat_copy_new ( int m, int n, double a1[] );
double r8vec_sum ( int n, double a[] );
double *smr00 ( );
double *smr01 ( );
double *smr02 ( );
double *smr03 ( );
double *smr04 ( );
double *smr05 ( );
double *smr06 ( );
double *smr07 ( );
double *smr08 ( );
double *smr09 ( );
double *smr10 ( );
double *smr11 ( );
double *smr12 ( );
double *smr13 ( );
double *smr14 ( );
double *smr15 ( );
double *smr16 ( );
double *smr17 ( );
double *smr18 ( );
double *smr19 ( );
double *smr20 ( );
double *smr21 ( );
double *smr22 ( );
double *smr23 ( );
double *smr24 ( );
double *smr25 ( );
double *smr26 ( );
double *smr27 ( );
double *smr28 ( );
double *smr29 ( );
double *smr30 ( );
double *smr31 ( );
double *smr32 ( );
double *smr33 ( );
double *smr34 ( );
double *smr35 ( );
double *smr36 ( );
double *smr37 ( );
double *smr38 ( );
double *smr39 ( );
double *smr40 ( );
double *smr41 ( );
double *smr42 ( );
double *smr43 ( );
double *smr44 ( );
double *smr45 ( );
double *smr46 ( );
double *smr47 ( );
double *smr48 ( );
double *smr49 ( );
double *smr50 ( );
double *smr51 ( );
double *smr52 ( );
double *smr53 ( );
double *smr54 ( );
double *smr55 ( );
double *square_minimal_rule ( int degree );
int square_minimal_rule_degree_max ( );
double square_minimal_rule_error_max ( int degree );
int square_minimal_rule_order ( int degree );
double squaresym_area ( );
double squaresym_monomial_integral ( int e[2] );
void timestamp ( );
